fun main(){
    var Rodrigo = Paciente("rodrigo", 22)
    Rodrigo.adicionarConsulta("manutenção do aparelho")
    Rodrigo.adicionarConsulta("exame de vista")
    Rodrigo.adicionarConsulta("exame de calvice")
    Rodrigo.adicionarConsulta("exame de colesterol")
    Rodrigo.adicionarConsulta("exame de sangue")
    Rodrigo.adicionarConsulta("exame de prostata")
    Rodrigo.adicionarConsulta("checkup")
    Rodrigo.adicionarConsulta("exame de coração")
    Rodrigo.adicionarConsulta("exame de fezes")
    Rodrigo.adicionarConsulta("exame de ouvido")
    Rodrigo.adicionarConsulta("arrancar dente")
    Rodrigo.adicionarConsulta("arrancar dente")
    Rodrigo.adicionarConsulta("arrancar dente")
    println("----------------------------")
    Rodrigo.exibirConsultas()
}